# scripts/onboard.py — the adaptation front door.
"""Draft a tenant bundle from an OpenAPI 3.x spec:

    .venv/bin/python scripts/onboard.py --spec data/fixtures/hotel-openapi.yaml \
        --out data/tenants/hotel-demo --name "Grand Hotel"

Prints the discovery report, then writes fail-closed data only:

  proposals.yaml   every draft status: proposed — NOTHING executes until
                   you review and commit approvals (ADR-005)
  policies.yaml    starter verdicts: reads ALLOW, mutating ALLOW (the
                   brain still gathers parameters and confirms side
                   effects), high-risk ESCALATE
  tenant.json      name/currency scaffold; persona fields for the owner
  intents/ knowledge/  empty dirs (owner fills)
  README.md        the review checklist

Then: scripts/validate_tenant.py <out> — the CI gate.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import yaml

from voiceagent.openapi_draft import (discovery_report, parse_openapi,
                                      write_proposals_yaml)

_README = """# Draft tenant bundle (generated by scripts/onboard.py)

Review checklist before this bundle goes live:

1. proposals.yaml — every entry is `status: proposed`. For each tool:
   - read the description; rewrite it in YOUR voice (the brain hears it)
   - add `preconditions:` where business rules demand them (e.g. a booking
     can only be cancelled before check-in)
   - flip `status: approved` only for tools you want LIVE, then COMMIT —
     the commit is the human approval (ADR-005)
2. policies.yaml — high-risk actions start ESCALATE; relax deliberately.
   Undeclared actions are DENY (least privilege).
3. tenant.json — fill the persona (role, tone, may_promise, never_say).
4. intents/ — add one YAML list of exemplar phrases per intent.
5. knowledge/ — add markdown docs (policies, FAQs) the agent may quote.
6. Validate: .venv/bin/python scripts/validate_tenant.py <this dir>
"""


def _slugify(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "tenant"


def _starter_policies(ops) -> str:
    lines = [
        "# DRAFT policy verdicts generated by scripts/onboard.py.",
        "# Reads: allowed. Mutating: allowed (the brain gathers parameters",
        "# and confirms side effects before executing). High-risk: ESCALATE",
        "# — review each and relax deliberately. Undeclared actions are",
        "# DENY (least privilege). The platform valves (escalate_to_human,",
        "# end_call) are always allowed by code, not by this file.", "",
    ]
    seen: set[str] = set()
    for op in ops:
        action = op["action"]
        if action in seen:
            continue
        seen.add(action)
        if op["risk_class"] == "high":
            lines.append(f"{action}:")
            lines.append("  escalate: true   # DRAFT — review")
        else:
            lines.append(f"{action}:")
            lines.append("  allow: true")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Draft a governed tenant bundle from an OpenAPI spec.")
    ap.add_argument("--spec", required=True,
                    help="OpenAPI 3.x file (.yaml or .json)")
    ap.add_argument("--out", required=True,
                    help="bundle directory to scaffold (e.g. "
                         "data/tenants/my-business)")
    ap.add_argument("--name", default=None,
                    help="tenant name (defaults to slugified info.title)")
    args = ap.parse_args(argv)

    spec_path = Path(args.spec)
    doc = yaml.safe_load(spec_path.read_text(encoding="utf-8"))
    result = parse_openapi(doc)
    title = (doc.get("info") or {}).get("title", "")
    print(discovery_report(result, title=title))

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    names = write_proposals_yaml(result, out / "proposals.yaml")
    (out / "policies.yaml").write_text(
        _starter_policies(result.operations), encoding="utf-8")
    bundle_name = args.name or title or "tenant"
    (out / "tenant.json").write_text(json.dumps({
        "name": bundle_name,
        "currency": "USD",
        "persona": f"{bundle_name}'s voice agent — help customers with "
                   "their requests.",
        "languages": ["en"],
        "greeting": f"Thank you for calling {bundle_name}. How can I help?",
    }, indent=2) + "\n", encoding="utf-8")
    (out / "intents").mkdir(exist_ok=True)
    (out / "knowledge").mkdir(exist_ok=True)
    (out / "README.md").write_text(_README, encoding="utf-8")

    print(f"\nWrote bundle scaffold to {out} with drafts: "
          f"{', '.join(names)}")
    print("Next: review proposals.yaml + policies.yaml, fill persona/"
          "intents/knowledge, then validate:")
    print(f"  .venv/bin/python scripts/validate_tenant.py {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
